name: vehicle-damage-assessment
services:
- name: backend
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  - path: /health
  - path: /docs
  - path: /redoc
  envs:
  - key: GEMINI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PORT
    scope: RUN_TIME
    value: "8000"
  health_check:
    http_path: /health

- name: frontend
  source_dir: /frontend
  github:
    repo: your-username/your-repo-name
    branch: main
  build_command: npm ci && npm run build
  run_command: npx serve -s build -p $PORT
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: ${backend.PUBLIC_URL}
  - key: PORT
    scope: RUN_TIME
    value: "3000"

static_sites: []
jobs: []
workers: []
databases: []
